@startuml
|Клиент|
start
:Формирование запроса на выбор технологий;
:Передача запроса менеджерам;

|Менеджеры|
:Анализ требований клиента;
:Постановка задачи аналитикам;
:Экспорт требований в CloudServise;

|CloudServise|
:Импорт требований из CloudServise;

|Аналитики|
:Поиск и обработка нужных документов;
:Работа с данными в Excel;
:Выбор критериев из требований;

|CloudServise|
:Экспорт нужных документов;

|Аналитики|
:Ранжирование технологий;
:Подготовка результатов;
:Импорт результатов в CloudServise;

|CloudServise|
:Импорт результатов;

|Менеджеры|
:Экспорт из CloudServise;
:Формирование рекомендаций клиенту;

|Клиент|
:Получение рекомендаций;

stop
@enduml
